### PR TITLE
[SO] Add content from week 1-2 

### PR DESCRIPTION
**Pull request by Pesteves2002**

### CODE REVIEW

**Comment by Pesteves2002** [comment]
Ready to merge, adiciono o resumo 0001 soon

**Comment by diogotcorreia** [comment]
I'll review this tomorrow! Awesome work :tada:

**Comment by Pesteves2002** [comment]
Don't PR yet

**Comment by Pesteves2002** [comment]
@RafDevX GIT REVIEW!!

**Comment by diogotcorreia** [comment]
I've reviewed the first page. I'll finish reviewing the other two pages tomorrow!

**Review by diogotcorreia — APPROVED** [review]

**Pull request merged**
